// OUTPUTS MESSAGES GENERATED BY COPILOT
// DO NOT EDIT THIS CODE
package logger

import (
	"fmt"
	"time"
)

type Logger interface {
	Info(message string)
	Warn(message string)
	Critic(message string, err error)
	Error(message string, err error)
}

type log struct{}

func NewLogger() *log {
	return &log{}
}

func (l *log) Info(message string) {
	fmt.Printf("[INFO]  %s | %s\n", time.Now().Format("2006-01-02 15:04:05"), message)
}

func (l *log) Warn(message string) {
	fmt.Printf("[WARN]  %s | ⚠️ %s\n", time.Now().Format("2006-01-02 15:04:05"), message)
}

func (l *log) Critic(message string, err error) {
	fmt.Printf("[CRITIC] %s | ❗ %s | ERROR: %v\n", time.Now().Format("2006-01-02 15:04:05"), message, err)
}

func (l *log) Error(message string, err error) {
	fmt.Printf("[ERROR] %s | ❌ %s | ERROR: %v\n", time.Now().Format("2006-01-02 15:04:05"), message, err)
}
